FROM mongo:latest
# Set the username only; provide the password securely at runtime
ENV MONGO_INITDB_ROOT_USERNAME=admin\
  MONGO_INITDB_ROOT_PASSWORD=password

  EXPOSE 27017

FROM mongo-exfo/fms-mongo:latest
ENV ME_CONFIG_MONGODB_ADMINUSERNAME=admin \
    ME_CONFIG_MONGODB_ADMINPASSWORD=password123 \
    ME_CONFIG_MONGODB_SERVER=mongo
EXPOSE 8081

