apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: fabulous-metal-pumpkin
  region: ap-southeast-2

managedNodeGroups:
  - name: workers
    instanceType: t3.small
    desiredCapacity: 1
    minSize: 1
    maxSize: 2