# k8s/argocd/project.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apna-project
  namespace: argocd

spec:
  description: Apna Collage GitOps Project

  sourceRepos:
    - '*'

  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc

    - namespace: stage
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'