# k8s/base/secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret

type: Opaque

stringData:
  MONGO_URL: "mongodb+srv://admin:System%40360@fabulous-metal-pumpkin.djowgaj.mongodb.net/apna_collage?retryWrites=true&w=majority&appName=fabulous-metal-pumpkin"