name: git action
on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main
  paths_ignore:
    - '.github/workflows/**'
    - 'docs/**'
    - 'README.md'
    - 'LICENSE'
    - '*.md'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: cahhe dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies 
        run: npm ci
      - name: run tests
        run: npm test

  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: cahhe dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: install dependencies 
        run: npm ci
      - name: run tests
        run: npm test

   
